name: Docker image build

on:
  workflow_call:
    inputs:
      is_default_flavor:
        required: false
        type: boolean
        description: |
          Whether this flavor becomes the default. Suffixless tags will be
          added if set to true.
      suffix:
        required: true
        type: string
        description: A suffix to append to the image tag.
      dockerfile:
        required: false
        type: string
        default: Dockerfile
        description: Path to Dockerfile to build image from.

jobs:
  docker:
    name: Build and publish to Docker Hub and GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          tags: |
            # branch event
            type=ref,event=branch,enable={{is_default_flavor}}
            type=ref,event=branch,suffix={{suffix}}
            # set latest tag for main branch
            type=raw,value=latest,enable=${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref && is_default_flavor }}
            type=raw,value=latest,suffix={{suffix}},enable={{is_default_branch}}
            # tag event
            type=ref,event=tag,enable={{is_default_flavor}}
            type=ref,event=tag,suffix={{suffix}}
          images: |
            ghcr.io/${{ github.repository_owner }}/ts3server
            icedream/ts3server
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: {{dockerfile}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
